version: 2.1

parameters:
  update_pcu:
    type: boolean
    default: false
    description: "If true, pcu is updated from its main github branch before running."

orbs:
  toolkit: jerus-org/circleci-toolkit@8.0.3

  orb-tools: circleci/orb-tools@12.5.0
  # >>> gen-circleci-orb (managed — edits overwritten by 'gen-circleci-orb update')
  gen-circleci-orb: jerus-org/gen-circleci-orb@0.2.4
  # <<< gen-circleci-orb
workflows:
  update_prlog:
    jobs:
      - toolkit/update_prlog:
          name: update-prlog-on-main
          context:
            - release
            - bot-check
            - pcu-app
          target_branch: "main"
          pcu_from_merge: --from-merge
          update_pcu: << pipeline.parameters.update_pcu >>
          pcu_verbosity: "-vvv"
      # >>> gen-circleci-orb (managed — edits overwritten by 'gen-circleci-orb update')
      - gen-circleci-orb/build_rust_binary:
          name: post-merge-build-binary
          package: jci-coverage
          executor: toolkit/rust_env_rolling
          requires: [update-prlog-on-main]
          pre-steps:
            - run:
                name: Check qualifying branch
                command: |
                  case "$CIRCLE_BRANCH" in
                    renovate/*) ;;
                    *) echo "Not a qualifying branch ($CIRCLE_BRANCH) - nothing to do."; circleci-agent step halt ;;
                  esac
      - gen-circleci-orb/generate:
          name: post-merge-check-orb
          binary: jci-coverage
          orb_namespace: jerus-org
          orb_dir: orb
          attach_workspace: true
          target_branch: main
          check: true
          persist_orb_workspace: true
          requires: [post-merge-build-binary]
          pre-steps:
            - run:
                name: Check qualifying branch
                command: |
                  case "$CIRCLE_BRANCH" in
                    renovate/*) ;;
                    *) echo "Not a qualifying branch ($CIRCLE_BRANCH) - nothing to do."; circleci-agent step halt ;;
                  esac
      - orb-tools/pack:
          name: post-merge-pack-orb
          checkout: false
          source_dir: orb/src
          pre-steps:
            - run:
                name: Check qualifying branch
                command: |
                  case "$CIRCLE_BRANCH" in
                    renovate/*) ;;
                    *) echo "Not a qualifying branch ($CIRCLE_BRANCH) - nothing to do."; circleci-agent step halt ;;
                  esac
            - attach_workspace:
                at: .
          requires: [post-merge-check-orb]
      - orb-tools/review:
          name: post-merge-review-orb
          checkout: false
          source_dir: orb/src
          pre-steps:
            - run:
                name: Check qualifying branch
                command: |
                  case "$CIRCLE_BRANCH" in
                    renovate/*) ;;
                    *) echo "Not a qualifying branch ($CIRCLE_BRANCH) - nothing to do."; circleci-agent step halt ;;
                  esac
            - attach_workspace:
                at: .
          requires: [post-merge-pack-orb]
      # <<< gen-circleci-orb
