//! # jci-coverage
//!
//! A CLI that generates source-based Rust code coverage with
//! [`cargo-llvm-cov`](https://crates.io/crates/cargo-llvm-cov) and uploads the
//! report to [OtterWise](https://getotterwise.com) for code quality
//! reporting.
//!
//! Two independent subcommands:
//!
//! - **`report`** — orchestrates `cargo llvm-cov` (shelling out to it, and to
//!   `cargo-nextest` when that runner is selected) to write
//!   `coverage/lcov.info` and print a terminal summary. Rust-specific.
//! - **`upload`** — takes a coverage file path and posts it to OtterWise. It
//!   never assumes `report` produced the file: a non-Rust project can run
//!   `upload` on its own, standalone, against a coverage report it generated by
//!   whatever means it already uses.
//!
//! Kept as two subcommands, not one, so the CLI surface (and OtterWise's
//! field mapping) can grow additional upload targets later without reshaping
//! coverage generation.

use anyhow::Result;
use clap::{Parser, Subcommand};

use crate::{report, upload};

/// Source-based Rust code coverage with OtterWise upload.
#[derive(Debug, Parser)]
#[command(name = "jci-coverage")]
#[command(
    author,
    version,
    about = "Source-based Rust code coverage with OtterWise upload",
    long_about = "Generate source-based Rust code coverage with cargo-llvm-cov \
        and upload the report to OtterWise for code quality reporting. \
        `report` and `upload` are independent: `upload` works standalone \
        against any coverage file, Rust or not.",
    term_width = 70
)]
pub struct Cli {
    #[command(flatten)]
    pub logging: clap_verbosity_flag::Verbosity<clap_verbosity_flag::InfoLevel>,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Generate a coverage report with cargo-llvm-cov.
    #[command(
        long_about = "Writes `coverage/lcov.info` and prints a terminal \
            summary. Requires `cargo-llvm-cov` and the `llvm-tools` rustup \
            component on PATH (and `cargo-nextest` too, when `--runner \
            nextest` is selected).",
        term_width = 70
    )]
    Report(report::ReportArgs),
    /// Upload a coverage report to OtterWise.
    #[command(
        long_about = "Standalone: takes a coverage file path and uploads \
            it. Does not require `report`, Rust, or `cargo-llvm-cov` — the \
            caller is responsible for the file existing at the given path \
            in a format OtterWise accepts.",
        term_width = 70
    )]
    Upload(upload::UploadArgs),
}

impl Cli {
    /// Execute the selected subcommand.
    pub fn run(&self) -> Result<()> {
        match &self.command {
            Commands::Report(args) => report::run(args),
            Commands::Upload(args) => upload::run(args),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    #[test]
    fn parse_report_defaults() {
        let cli = Cli::try_parse_from(["jci-coverage", "report"]).expect("report parses");
        match cli.command {
            Commands::Report(args) => {
                assert_eq!(args.package, None);
                assert_eq!(args.runner, report::Runner::Test);
                assert_eq!(args.nextest_profile, None);
                assert!(!args.no_all_features, "--all-features is on by default");
            }
            other => panic!("expected Report, got {other:?}"),
        }
    }

    #[test]
    fn parse_report_nextest_runner() {
        let cli =
            Cli::try_parse_from(["jci-coverage", "report", "--runner", "nextest"]).expect("parses");
        match cli.command {
            Commands::Report(args) => assert_eq!(args.runner, report::Runner::Nextest),
            other => panic!("expected Report, got {other:?}"),
        }
    }

    #[test]
    fn upload_requires_file() {
        assert!(Cli::try_parse_from(["jci-coverage", "upload"]).is_err());
        let cli = Cli::try_parse_from(["jci-coverage", "upload", "--file", "coverage/lcov.info"])
            .expect("parses");
        match cli.command {
            Commands::Upload(args) => {
                assert_eq!(args.file, PathBuf::from("coverage/lcov.info"));
            }
            other => panic!("expected Upload, got {other:?}"),
        }
    }

    #[test]
    fn upload_does_not_require_rust_or_report_context() {
        // No --package, --runner, or any report-only flag exists on upload —
        // it stands alone. This test pins that by asserting a report-only
        // flag is rejected on upload.
        let err = Cli::try_parse_from([
            "jci-coverage",
            "upload",
            "--file",
            "coverage.out",
            "--runner",
            "test",
        ])
        .unwrap_err();
        assert!(err.to_string().contains("runner"));
    }

    #[test]
    fn every_subcommand_has_a_long_about_distinct_from_its_about() {
        use clap::CommandFactory;
        let cmd = Cli::command();
        for name in ["report", "upload"] {
            let sub = cmd
                .find_subcommand(name)
                .unwrap_or_else(|| panic!("no '{name}' subcommand"));
            let about = sub.get_about().map(ToString::to_string);
            let long_about = sub.get_long_about().map(ToString::to_string);
            assert!(
                long_about.is_some() && long_about != about,
                "'{name}': long_about must be set and differ from about (about: {about:?})"
            );
        }
    }

    #[test]
    fn unknown_subcommand_is_error() {
        assert!(Cli::try_parse_from(["jci-coverage", "bogus"]).is_err());
    }
}
